'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Setting() As String
            Get
                Return CType(Me("Setting"),String)
            End Get
            Set
                Me("Setting") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://www.google.com/search?client=jumpgo&ie=UTF-8&oe=UTF-8&q=")>  _
        Public Property Search() As String
            Get
                Return CType(Me("Search"),String)
            End Get
            Set
                Me("Search") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://www.google.com/search?client=jumpgo&ie=UTF-8&oe=UTF-8&q=")>  _
        Public Property Google() As String
            Get
                Return CType(Me("Google"),String)
            End Get
            Set
                Me("Google") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://search.yahoo.com/search;_ylt=AtBw7aX_oxzoq6VqvLov.5WbvZx4?p=")>  _
        Public Property Yahoo() As String
            Get
                Return CType(Me("Yahoo"),String)
            End Get
            Set
                Me("Yahoo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://www.bing.com/search?q=google&go=Submit&qs=n&form=QBLH&pq=")>  _
        Public Property Bing() As String
            Get
                Return CType(Me("Bing"),String)
            End Get
            Set
                Me("Bing") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UserSearch() As String
            Get
                Return CType(Me("UserSearch"),String)
            End Get
            Set
                Me("UserSearch") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://www.google.com/")>  _
        Public Property Home() As String
            Get
                Return CType(Me("Home"),String)
            End Get
            Set
                Me("Home") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://www.google.com/")>  _
        Public Property NewTab() As String
            Get
                Return CType(Me("NewTab"),String)
            End Get
            Set
                Me("NewTab") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property FirstRun() As Boolean
            Get
                Return CType(Me("FirstRun"),Boolean)
            End Get
            Set
                Me("FirstRun") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property NavPanelBG() As String
            Get
                Return CType(Me("NavPanelBG"),String)
            End Get
            Set
                Me("NavPanelBG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MenuPanelBG() As String
            Get
                Return CType(Me("MenuPanelBG"),String)
            End Get
            Set
                Me("MenuPanelBG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Dark")>  _
        Public Property ThemeColor() As String
            Get
                Return CType(Me("ThemeColor"),String)
            End Get
            Set
                Me("ThemeColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("797, 510")>  _
        Public Property LastSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("LastSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("LastSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property WebApps() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("WebApps"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("WebApps") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <s"& _ 
            "tring>https://www.google.com/</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ArrayOfString>")>  _
        Public Property Bookmarks() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Bookmarks"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("Bookmarks") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property HighContrast() As Boolean
            Get
                Return CType(Me("HighContrast"),Boolean)
            End Get
            Set
                Me("HighContrast") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Beta")>  _
        Public Property Client() As String
            Get
                Return CType(Me("Client"),String)
            End Get
            Set
                Me("Client") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://raw.githubusercontent.com/JTechMe/DotNET-Updater-Files/master/JGDEB.xml")>  _
        Public Property BetaClient() As String
            Get
                Return CType(Me("BetaClient"),String)
            End Get
            Set
                Me("BetaClient") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://raw.githubusercontent.com/JTechMe/DotNET-Updater-Files/master/JGDES.xml")>  _
        Public Property StableClient() As String
            Get
                Return CType(Me("StableClient"),String)
            End Get
            Set
                Me("StableClient") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("JG4")>  _
        Public Property SetIcon() As String
            Get
                Return CType(Me("SetIcon"),String)
            End Get
            Set
                Me("SetIcon") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property WebHistory() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("WebHistory"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("WebHistory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://developers.google.com/s/results/?q=")>  _
        Public Property GoogleDevelopersSearch() As String
            Get
                Return CType(Me("GoogleDevelopersSearch"),String)
            End Get
            Set
                Me("GoogleDevelopersSearch") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://en.wikipedia.org/w/index.php?title=Special%3ASearch&profile=default&searc"& _ 
            "h=")>  _
        Public Property WikipediaSearch() As String
            Get
                Return CType(Me("WikipediaSearch"),String)
            End Get
            Set
                Me("WikipediaSearch") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("&fulltext=Search")>  _
        Public Property WikipediaSearchPt2() As String
            Get
                Return CType(Me("WikipediaSearchPt2"),String)
            End Get
            Set
                Me("WikipediaSearchPt2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://github.com/search?utf8=✓&q=")>  _
        Public Property GitHubSearch() As String
            Get
                Return CType(Me("GitHubSearch"),String)
            End Get
            Set
                Me("GitHubSearch") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://www.youtube.com/results?search_query=")>  _
        Public Property YouTubeSearch() As String
            Get
                Return CType(Me("YouTubeSearch"),String)
            End Get
            Set
                Me("YouTubeSearch") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://duckduckgo.com/?t=jumpgo&q=")>  _
        Public Property DuckDuckGoSearch() As String
            Get
                Return CType(Me("DuckDuckGoSearch"),String)
            End Get
            Set
                Me("DuckDuckGoSearch") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://stackoverflow.com/search?q=")>  _
        Public Property StackOverflowSearch() As String
            Get
                Return CType(Me("StackOverflowSearch"),String)
            End Get
            Set
                Me("StackOverflowSearch") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SavedLinks() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("SavedLinks"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("SavedLinks") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CurVerIDAvai() As String
            Get
                Return CType(Me("CurVerIDAvai"),String)
            End Get
            Set
                Me("CurVerIDAvai") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("normal")>  _
        Public Property LastWinState() As String
            Get
                Return CType(Me("LastWinState"),String)
            End Get
            Set
                Me("LastWinState") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AeroTabs() As Boolean
            Get
                Return CType(Me("AeroTabs"),Boolean)
            End Get
            Set
                Me("AeroTabs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NavPnlBGEnabled() As Boolean
            Get
                Return CType(Me("NavPnlBGEnabled"),Boolean)
            End Get
            Set
                Me("NavPnlBGEnabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property FavList() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("FavList"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("FavList") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.JumpGoStandardEdition.My.MySettings
            Get
                Return Global.JumpGoStandardEdition.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
